// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "alisa-gpt/internal/models"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// Chat provides a mock function with given fields: ctx, messages
func (_m *Client) Chat(ctx context.Context, messages []models.Message) (string, error) {
	ret := _m.Called(ctx, messages)

	if len(ret) == 0 {
		panic("no return value specified for Chat")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []models.Message) (string, error)); ok {
		return rf(ctx, messages)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []models.Message) string); ok {
		r0 = rf(ctx, messages)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []models.Message) error); ok {
		r1 = rf(ctx, messages)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Client_Chat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chat'
type Client_Chat_Call struct {
	*mock.Call
}

// Chat is a helper method to define mock.On call
//   - ctx context.Context
//   - messages []models.Message
func (_e *Client_Expecter) Chat(ctx interface{}, messages interface{}) *Client_Chat_Call {
	return &Client_Chat_Call{Call: _e.mock.On("Chat", ctx, messages)}
}

func (_c *Client_Chat_Call) Run(run func(ctx context.Context, messages []models.Message)) *Client_Chat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]models.Message))
	})
	return _c
}

func (_c *Client_Chat_Call) Return(_a0 string, _a1 error) *Client_Chat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Client_Chat_Call) RunAndReturn(run func(context.Context, []models.Message) (string, error)) *Client_Chat_Call {
	_c.Call.Return(run)
	return _c
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
